export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const INVALID_LOGIN = "INVALID_LOGIN";
export const LOGIN_NETWORK_ERROR = "LOGIN_NETWORK_ERROR";
export const LOGOUT = "LOGOUT";
export const READ_THREADS = "READ_THREADS";